const MIN_PLAYER_NAME_LENGTH = 5;
const MIN_PLAYER_PASS_LENGTH = 5;
const MAX_PLAYER_NAME_LENGTH = 15;
const MAX_PLAYER_PASS_LENGTH = 20;

export {
  MIN_PLAYER_NAME_LENGTH,
  MIN_PLAYER_PASS_LENGTH,
  MAX_PLAYER_NAME_LENGTH,
  MAX_PLAYER_PASS_LENGTH
};
